language: rust
cache: cargo
rust: stable

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo fmt --version
  - cargo clippy --version

script:
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test  --verbose
  - cargo clippy -- -D clippy::all
